// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdhldvlbomfkifjwiheo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaGxkdmxib21ma2lmandpaGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQ0ODcsImV4cCI6MjA3MTQ3MDQ4N30.PYhLI4sCwXigV9DIJVyDmdUIfoBnx9ixlO6Bo99EPTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});